// Embed the built host bundle (a single self-contained HTML) as a TypeScript
// string module the provider can hand to the WebView. Regenerate the whole
// chain with `npm run rn:host` (builds the host, then runs this).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const htmlPath = join(here, "../host/dist/index.html");
const outPath = join(here, "../src/host-html.ts");

const html = readFileSync(htmlPath, "utf8");
const contents =
  "// GENERATED by scripts/embed-host.mjs — do not edit. Regenerate with `npm run rn:host`.\n" +
  `export const HOST_HTML: string = ${JSON.stringify(html)};\n`;
writeFileSync(outPath, contents);
console.log(`Embedded ${(html.length / 1024).toFixed(0)} KB -> src/host-html.ts`);
