/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_addmessages_free: (a: number, b: number) => void;
export const __wbg_group_free: (a: number, b: number) => void;
export const __wbg_identity_free: (a: number, b: number) => void;
export const __wbg_keypackage_free: (a: number, b: number) => void;
export const __wbg_nowelcomeerror_free: (a: number, b: number) => void;
export const __wbg_provider_free: (a: number, b: number) => void;
export const __wbg_ratchettree_free: (a: number, b: number) => void;
export const addmessages_commit: (a: number) => any;
export const addmessages_proposal: (a: number) => any;
export const addmessages_welcome: (a: number) => any;
export const group_create_message: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const group_create_new: (a: number, b: number, c: number, d: number) => number;
export const group_export_key: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const group_export_ratchet_tree: (a: number) => number;
export const group_join: (a: number, b: number, c: number, d: number) => [number, number, number];
export const group_merge_pending_commit: (a: number, b: number) => [number, number];
export const group_process_message: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const group_propose_and_commit_add: (a: number, b: number, c: number, d: number) => [number, number, number];
export const identity_key_package: (a: number, b: number) => number;
export const identity_new: (a: number, b: number, c: number) => [number, number, number];
export const keypackage_from_bytes: (a: number, b: number) => [number, number, number];
export const keypackage_to_bytes: (a: number) => [number, number];
export const provider_new: () => number;
export const ratchettree_from_bytes: (a: number, b: number) => [number, number, number];
export const ratchettree_to_bytes: (a: number) => [number, number];
export const greet: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
